load("@rules_shell//shell:sh_test.bzl", "sh_test")

sh_test(
    name = "lock-base-image",
    srcs = ["test.sh"],
    data = [
        "//tools:dnf5lock",
    ] + glob(["etc/**/*", "usr/**/*"]),
    deps = ["@rules_shell//shell/runfiles"],
    tags = [
        "requires-network"
    ],
    exec_properties = {
        "dockerNetwork":"bridge",  # make sure buildbuddy rbe allows internet access
    },
)
