load("@bazel_skylib//rules:write_file.bzl", "write_file")

def write_rpm_config_h(name):
    content = [
        "/* Generated config.h for rpm Bazel build */",
        "#ifndef RPM_CONFIG_H",
        "#define RPM_CONFIG_H",
        "",
        "#define PACKAGE \"rpm\"",
        "#define VERSION \"6.0.90\"",
        "#define PACKAGE_BUGREPORT \"http://rpm.org\"",
        "#define RPM_VENDOR \"vendor\"",
        "",
        "#define UID_0_USER \"root\"",
        "#define GID_0_GROUP \"root\"",
        "#define C_LOCALE \"C.UTF-8\"",
        "",
        "/* Features */",
        "#define ENABLE_SQLITE 1",
        "",
        "/* Dependencies */",
        "#define HAVE_BZLIB_H 1",
        "#define HAVE_LZMA_H 1",
        "#define HAVE_ZSTD 1",
        "#define HAVE_ZLIB_H 1",
        "#define HAVE_LIBCRYPTO 1",
        "#define HAVE_OPENSSL_EVP_H 1",
        "",
        "/* POSIX headers */",
        "#define HAVE_DIRENT_H 1",
        "#define HAVE_DLFCN_H 1",
        "#define HAVE_INTTYPES_H 1",
        "#define HAVE_LIMITS_H 1",
        "#define HAVE_MEMORY_H 1",
        "#define HAVE_PTHREAD_H 1",
        "#define HAVE_STDINT_H 1",
        "#define HAVE_STDLIB_H 1",
        "#define HAVE_STRINGS_H 1",
        "#define HAVE_STRING_H 1",
        "#define HAVE_SYS_DIR_H 1",
        "#define HAVE_SYS_PARAM_H 1",
        "#define HAVE_SYS_STAT_H 1",
        "#define HAVE_SYS_TYPES_H 1",
        "#define HAVE_SYS_UTSNAME_H 1",
        "#define HAVE_UNISTD_H 1",
        "",
        "/* POSIX functions */",
        "#define HAVE_BASENAME 1",
        "#define HAVE_DIRNAME 1",
        "#define HAVE_FDATASYNC 1",
        "#define HAVE_FCHMODAT 1",
        "#define HAVE_FCHOWNAT 1",
        "#define HAVE_FSTATAT 1",
        "#define HAVE_GETADDRINFO 1",
        "#define HAVE_GETCWD 1",
        "#define HAVE_GETLINE 1",
        "#define HAVE_GETOPT_H 1",
        "#define HAVE_LINKAT 1",
        "#define HAVE_LOCALTIME_R 1",
        "#define HAVE_MEMPCPY 1",
        "#define HAVE_MERGESORT 1",
        "#define HAVE_MKDIRAT 1",
        "#define HAVE_MKFIFOAT 1",
        "#define HAVE_MKNODAT 1",
        "#define HAVE_MKSTEMP 1",
        "#define HAVE_OPENAT 1",
        "#define HAVE_PUTENV 1",
        "#define HAVE_REALPATH 1",
        "#define HAVE_REGCOMP 1",
        "#define HAVE_RENAMEAT 1",
        "#define HAVE_SECURE_GETENV 1",
        "#define HAVE_SETENV 1",
        "#define HAVE_STATVFS 1",
        "#define HAVE_STPCPY 1",
        "#define HAVE_STPNCPY 1",
        "#define HAVE_STRUCT_DIRENT_D_TYPE 1",
        "#define HAVE_SYMLINKAT 1",
        "#define HAVE_SYS_SYSMACROS_H 1",
        "#define MAJOR_IN_SYSMACROS 1",
        "#define HAVE_UNLINKAT 1",
        "#define HAVE_UNSETENV 1",
        "#define HAVE_UTIMENSAT 1",
        "#define HAVE_UTIMES 1",
        "#define HAVE___PROGNAME 1",
        "#define HAVE___SECURE_GETENV 1",
        "",
        "#ifdef __linux__",
        "#define HAVE_SCHED_GETAFFINITY 1",
        "#define HAVE_UNSHARE 1",
        "#define HAVE_SYNCFS 1",
        "#define HAVE_MREMAP 1",
        "#endif",
        "",
        "#ifdef __APPLE__",
        "#define HAVE_LUTIMES 1",
        "#endif",
        "",
        "#endif /* RPM_CONFIG_H */",
        ""
    ]

    write_file(
        name = name,
        out = "config.h",
        content = content,
    )
