load("@bazel_skylib//rules:expand_template.bzl", "expand_template")

def rpm_expand_template(name, template, out):
    # Standard CMake configure replacements for rpm
    substitutions = {
        "@VERSION@": "6.0.90",
        "@RPMCANONVENDOR@": "vendor",
        "@RPMCANONOS@": "linux",
        "@RPMCANONGNU@": "-gnu",
        "@__7ZIP@": "/usr/bin/7z",
        "@__BZIP2@": "/usr/bin/bzip2",
        "@__CAT@": "/usr/bin/cat",
        "@__CHMOD@": "/usr/bin/chmod",
        "@__CHOWN@": "/usr/bin/chown",
        "@__CP@": "/usr/bin/cp",
        "@__FILE@": "/usr/bin/file",
        "@__GPG@": "/usr/bin/gpg",
        "@__GREP@": "/usr/bin/grep",
        "@__GZIP@": "/usr/bin/gzip",
        "@__ID@": "/usr/bin/id",
        "@__INSTALL@": "/usr/bin/install",
        "@__LN@": "/usr/bin/ln",
        "@__LRZIP@": "/usr/bin/lrzip",
        "@__LZIP@": "/usr/bin/lzip",
        "@__MAKE@": "/usr/bin/make",
        "@__MKDIR@": "/usr/bin/mkdir",
        "@__MV@": "/usr/bin/mv",
        "@__PATCH@": "/usr/bin/patch",
        "@__RM@": "/usr/bin/rm",
        "@__SED@": "/usr/bin/sed",
        "@__TAR@": "/usr/bin/tar",
        "@__UNZIP@": "/usr/bin/unzip",
        "@__XZ@": "/usr/bin/xz",
        "@__ZSTD@": "/usr/bin/zstd",
        "@__AWK@": "/usr/bin/awk",
        "@prefix@": "/usr",
        "@exec_prefix@": "/usr",
        "@bindir@": "/usr/bin",
        "@sbindir@": "/usr/sbin",
        "@libexecdir@": "/usr/libexec",
        "@datarootdir@": "/usr/share",
        "@datadir@": "/usr/share",
        "@sysconfdir@": "/etc",
        "@sharedstatedir@": "/var/lib",
        "@localstatedir@": "/var",
        "@libdir@": "/usr/lib",
        "@includedir@": "/usr/include",
        "@infodir@": "/usr/share/info",
        "@mandir@": "/usr/share/man",
        "@RUNDIR@": "/run",
        "@rundir@": "/run",
    }
    
    expand_template(
        name = name,
        template = template,
        out = out,
        substitutions = substitutions,
    )
